rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: true
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.lang.live/room/5664344
  is_listening: false
  quality: 0
- url: https://live.bilibili.com/22603245
  is_listening: false
  quality: 0
- url: https://www.douyu.com/topic/jccs95match?rid=11608886&dyshid=0-c74c82500bdaa7990ec4710000021601
  is_listening: false
  quality: 0
- url: https://www.douyu.com/3357246?dyshid=0-c74c82500bdaa7990ec4710000021601&dyshci=33
  is_listening: false
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000
